### ISSUE TITLE
cv2.error:Opencv(3.4.10)

### ISSUE THREAD

**Issue by boringKey** [zhiyuanyou/UniAD#12]
thanks for your excellent work
I still met  a  question as follows：
cv2.error:Opencv(3.4.10) /tmp/pip-req-build-806eaxqo-opencv/modules/imgproc/src/colot.cpp:182........

**Comment by zhiyuanyou** [comment]
Hi, I cannot analyze why just from what you put here. Could you please put **_all messages_**?

**Comment by boringKey** [comment]
![0a93c95b2667cebf43a89f00d1920ed](https://user-images.githubusercontent.com/52984772/200479494-2817917e-5975-41ce-82fe-b45816e50769.jpg)
![81f6b3ae307882666ff5c953187b542](https://user-images.githubusercontent.com/52984772/200479500-c55be53c-d969-44e0-a689-00faae2fe048.jpg)

**Comment by boringKey** [comment]
Actually, I can use " sh train_torch.sh 1 0 " normally. But as you see,  when I read the 78th image in the 1st epoch, I will get the fault.

**Comment by zhiyuanyou** [comment]
In my view, this is because an image is corrupted. 
I suggest you:
- add a `print(filename)` in Line 96 of `datasets/custom_dataset.py` to find which image is corrupted. 
- write a script to read this image and convert its color to see whether it could succeed.

**Comment by boringKey** [comment]
Thank you for your patience! I'll have to give it a try.

**Comment by boringKey** [comment]
Ha! I deleted the old dataset and downloaded another new one and I overcame the issue we mentioned before. Actually, I got another question to ask you, my bro. How can I debug the code in Pycharm? I do need to observe the details, such as the shapes of some data in the code. Sorry to bother you again!

**Comment by zhiyuanyou** [comment]
Hi~
I do not have advice. I like using print & log to debug instead of different IDEs.

**Comment by Kboring** [comment]
Hi, I guess I need to bother you again, bro! I wonder know that do the "uniad" play a role in the process of visualizing feature reconstruction?  I find that you use Resnet to replace the UniAD in the model. In this way, I guess the structure of Transformer do not function in the process of visualizing feature reconstruction. Sincerely hoping your early reply!  Thank you~

**Comment by zhiyuanyou** [comment]
- Why do we need to train decoders (your mentioned ***Resnet***)? 

We follow a feature-reconstruction paradigm. The reconstruction source and target are all features. These features are hard to visualize, especially hard to show the "shortcut problem". Therefore, we need some decoders (your mentioned ***Resnet***) to project these features to pixel space. So, these decoders (your mentioned ***Resnet***) are trained to ***project backbone-extracted features to pixel space***. 

Please also see #9 for details. 

- What does UniAD function? 

The inputs of these decoders (your mentioned ***Resnet***), *i.e.*, reconstructed features, are produced and saved by UniAD.

**Comment by boringKey** [comment]
Oh, just a few minutes ago, I found the answers as you replied, so I deleted the question. Thank you so much for your timely respond!
