### ISSUE TITLE
When replacing the backbone, the loss becomes smaller

### ISSUE THREAD

**Issue by fuweifuvtoo** [zhiyuanyou/UniAD#15]
hello，when I replace backbone to reset,  the loss becomes less than 1 at the very beginning，which is different from efficient, is that normal?

**Comment by fuweifuvtoo** [comment]
if it is normal, why such a huge difference in loss?

**Comment by zhiyuanyou** [comment]
Hi~
It is normal. I guess this reflects that **_the features extracted by EfficientNet are harder to reconstruct than ResNet_**, which indicates more information. Thus the performance of EfficientNet is better than ResNet.

**Comment by chihhuiho** [comment]
Hello~ Thanks for the nice work and code. I was trying to reproduce the (image/pixel) auroc for ResNet50 and ResNet101, which are (92.4/96) and (92.2/95.9) in the paper, respectively. However, with the provided config file in MVTec folder and the suggested layer changes (https://github.com/zhiyuanyou/UniAD/blob/main/experiments/MVTec-AD/config.yaml#L89), the reproduced result for  ResNet50 and ResNet101 are (86.6/94.1) and (87.19/94.66). Could you please provide the config file and checkpoint for resnet50 and resnet101? Thank you in advance.
