### ISSUE TITLE
如何用自己的数据集测试

### ISSUE THREAD

**Issue by gwp2021** [zhiyuanyou/UniAD#16]
非常感谢您的分享，您创新性的工作让我耳目一新。我之前用MVTec测试了一遍，效果很好。但是我想用我自己创建的数据集测试时遇到了一些困难，您能分享一下如何对代码进行修改，从而检测自己的数据吗？非常感谢！

**Comment by zhiyuanyou** [comment]
Hi～
- 首先，你应该将数据集组成json文件的格式。
   你可以参考：https://github.com/zhiyuanyou/UniAD/blob/main/data/MVTec-AD/train.json 或 https://github.com/zhiyuanyou/UniAD/blob/main/data/MVTec-AD/test.json 。其中：
  - 如果没有分割标签，则不需要*maskname*字段。
  - 如果只有一类，则只需要设置一个*clsname*。
- 之后，复制`./experiments/MVTec-AD`文件夹作为你的实验文件夹，修改其中`config.yaml`的*config.dataset.image_reader.kwargs.image_dir*，*config.dataset.train.meta_file*，*config.dataset.test.meta_file*。
  - *config.dataset.train.meta_file*和*config.dataset.test.meta_file*应该设置为数据集的json文件路径。
  - *config.dataset.image_reader.kwargs.image_dir*和json文件中的*filename*字段合起来应该为图片的路径。
- 训练和测试的步骤与MVTec-AD相同。

**Comment by gwp2021** [comment]
Thank you so much for your reply, and please forgive me for taking so long to reply, it is due to Covid-19, you know.
According to your reply, I successfully trained my own data, but I have some doubts about the test results.
First, the result picture after the test is shown as follows, it is  in the " vis_compound" folder. My understanding is that the first one is the input, the blank in the second chapter should be gt, the third one is the anomaly localization, and the fourth one is the detection result of avg-pooling.

Second, the result of vis-recon in the "vis_recon/result_vis_recon" folder is shown below. Is the result of this reconstruction correct? 

I also wonder how you saved the input、 recon and pred results directly in one graph.
It is very presumptuous to ask so many questions. I'm looking forward to your reply！

**Comment by zhiyuanyou** [comment]
- 可视化结果
  - 第一张图是输入图像
  - 第二张是Ground Truth (如果没有分割标签的话，全白代表缺陷，全黑代表正常)
  - 第三张是定位结果 (将全部图片的最小值和最大值正则化到0和1，可以加最大值和最小值的threshold进行截断以避免过大值的干扰，使可视化结果更好看)
  - 第四张是参考图像 (将当前图片的最小值和最大值正则化到0和1，仅仅用于分析)

- 重构结果
  - 建议每一类训练一个单独的vis_decoder进行重构结果的可视化，可视化的效果会更好。

- 如何储存在一起
  - 将这些的图像储存、读取、截取所需要的部分、最后合并。

**Comment by gwp2021** [comment]
非常感谢您的回复，祝您毕业顺利！

**Comment by gwp2021** [comment]
> * 可视化结果
>   
>   * 第一张图是输入图像
>   * 第二张是Ground Truth (如果没有分割标签的话，全白代表缺陷，全黑代表正常)
>   * 第三张是定位结果 (将全部图片的最小值和最大值正则化到0和1，可以加最大值和最小值的threshold进行截断以避免过大值的干扰，使可视化结果更好看)
>   * 第四张是参考图像 (将当前图片的最小值和最大值正则化到0和1，仅仅用于分析)
> * 重构结果
>   
>   * 建议每一类训练一个单独的vis_decoder进行重构结果的可视化，可视化的效果会更好。
> * 如何储存在一起
>   
>   * 将这些的图像储存、读取、截取所需要的部分、最后合并。

我还有一个疑问，是否需要根据不同的数据来调整判断检测结果正负的阈值呢？我在代码中好像没找到相关的部分，还希望您解释一下。非常感谢！

**Comment by zhiyuanyou** [comment]
论文中的指标AUROC是与阈值无关的，所以作为论文开源的代码也就没有阈值。
实际使用的时候需要设置一个阈值，对于整张图的得分进行对比，以确定是否是缺陷。

**Comment by gwp2021** [comment]
感谢您的回复！
还想请教您，模型训练时已经对编码、解码器进行了训练，为什么之后还要单独训练Decoder？


莫名
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "zhiyuanyou/UniAD"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Feb 24, 2023 01:37 PM
***@***.***&gt;;
Cc:&nbsp;"郭维平(Weiping ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [zhiyuanyou/UniAD] 如何用自己的数据集测试 (Issue #16)





 
论文中的指标AUROC是与阈值无关的，所以作为论文开源的代码也就没有阈值。
 实际使用的时候需要设置一个阈值，对于整张图的得分进行对比，以确定是否是缺陷。

**Comment by zhiyuanyou** [comment]
这个vis_decoder是用于将特征可视化的（与UniAD模型中的encoder和decoder不同），与模型推理无关。


特征可视化主要是为了写论文的时候证明自己的思路，写一个完整的论文。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhiyuanyou/UniAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 下午3:07
***@***.***&gt;;
抄送:&nbsp;"尤志远 (Zhiyuan ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [zhiyuanyou/UniAD] 如何用自己的数据集测试 (Issue #16)





 感谢您的回复！ 
 还想请教您，模型训练时已经对编码、解码器进行了训练，为什么之后还要单独训练Decoder？ 
 
 
 莫名 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From:                                                                                                                        "zhiyuanyou/UniAD"                                                                                    ***@***.***&amp;gt;; 
 Date:&amp;nbsp;Fri, Feb 24, 2023 01:37 PM 
 ***@***.***&amp;gt;; 
 Cc:&amp;nbsp;"郭维平(Weiping ***@***.******@***.***&amp;gt;; 
 Subject:&amp;nbsp;Re: [zhiyuanyou/UniAD] 如何用自己的数据集测试 (Issue #16) 
 
 
 
 
 
   
 论文中的指标AUROC是与阈值无关的，所以作为论文开源的代码也就没有阈值。 
  实际使用的时候需要设置一个阈值，对于整张图的得分进行对比，以确定是否是缺陷。

**Comment by gwp2021** [comment]
> 这个vis_decoder是用于将特征可视化的（与UniAD模型中的encoder和decoder不同），与模型推理无关。 特征可视化主要是为了写论文的时候证明自己的思路，写一个完整的论文。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhiyuanyou/UniAD" ***@***.***&gt;; 发送时间:&nbsp;2023年2月24日(星期五) 下午3:07 ***@***.***&gt;; 抄送:&nbsp;"尤志远 (Zhiyuan ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [zhiyuanyou/UniAD] 如何用自己的数据集测试 (Issue #16) 感谢您的回复！ 还想请教您，模型训练时已经对编码、解码器进行了训练，为什么之后还要单独训练Decoder？ 莫名 ***@***.*** &amp;nbsp;
> ------------------&amp;nbsp;Original&amp;nbsp;------------------ From: "zhiyuanyou/UniAD" ***@***.***&amp;gt;; Date:&amp;nbsp;Fri, Feb 24, 2023 01:37 PM ***@***.***&amp;gt;; Cc:&amp;nbsp;"郭维平(Weiping ***@***.******@***.***&amp;gt;; Subject:&amp;nbsp;Re: [zhiyuanyou/UniAD] 如何用自己的数据集测试 (Issue #16) 论文中的指标AUROC是与阈值无关的，所以作为论文开源的代码也就没有阈值。 实际使用的时候需要设置一个阈值，对于整张图的得分进行对比，以确定是否是缺陷。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

- [

> url

`)

> 这个vis_decoder是用于将特征可视化的（与UniAD模型中的encoder和decoder不同），与模型推理无关。 特征可视化主要是为了写论文的时候证明自己的思路，写一个完整的论文。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhiyuanyou/UniAD" ***@***.***&gt;; 发送时间:&nbsp;2023年2月24日(星期五) 下午3:07 ***@***.***&gt;; 抄送:&nbsp;"尤志远 (Zhiyuan ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [zhiyuanyou/UniAD] 如何用自己的数据集测试 (Issue #16) 感谢您的回复！ 还想请教您，模型训练时已经对编码、解码器进行了训练，为什么之后还要单独训练Decoder？ 莫名 ***@***.*** &amp;nbsp;
> ------------------&amp;nbsp;Original&amp;nbsp;------------------ From: "zhiyuanyou/UniAD" ***@***.***&amp;gt;; Date:&amp;nbsp;Fri, Feb 24, 2023 01:37 PM ***@***.***&amp;gt;; Cc:&amp;nbsp;"郭维平(Weiping ***@***.******@***.***&amp;gt;; Subject:&amp;nbsp;Re: [zhiyuanyou/UniAD] 如何用自己的数据集测试 (Issue #16) 论文中的指标AUROC是与阈值无关的，所以作为论文开源的代码也就没有阈值。 实际使用的时候需要设置一个阈值，对于整张图的得分进行对比，以确定是否是缺陷。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

dump()输出的npz文件中，'pred'是异常得分图s吧？若进行异常检测推理，对其进行平均池化然后取均值/最大值即为该图总异常得分，可以这样理解吗？再次打扰您，非常抱歉！

**Comment by zhiyuanyou** [comment]
Please See Sec. 3.1 (*Explanation of Evaluation Results*) in README.
