### ISSUE TITLE
TypeError: efficientnet_b4() got an unexpected keyword argument 'outlayers'

### ISSUE THREAD

**Issue by helevor** [zhiyuanyou/UniAD#23]
Hello,
I'm trying to execute and understand your code and I have the following error : 
TypeError: efficientnet_b4() got an unexpected keyword argument 'outlayers'

In config.yaml there is :
    - name: backbone
      type: models.backbones.efficientnet_b4
      frozen: True
      kwargs:
        pretrained: True
        # select outlayers from: resnet [1,2,3,4], efficientnet [1,2,3,4,5]
        # empirically, for industrial: resnet [1,2,3] or [2,3], efficientnet [1,2,3,4] or [2,3,4]
        outlayers: [1,2,3,4]

However, when looking in the efficientnet directory, no file contain "outlayers". Where is this argument defined ?

Could you help to solve this error ?

**Comment by zhiyuanyou** [comment]
Hi~

Please see https://github.com/zhiyuanyou/UniAD/blob/main/tools/train_val.py#L48 and https://github.com/zhiyuanyou/UniAD/blob/main/utils/misc_helper.py#L182.

The _outlayers_ will be replaced by _blocks_.

**Comment by zhiyuanyou** [comment]
Well, if you did not revise anything, this error could not happen. 

So could you provide more information of your experiments, _i.e._, you run which shell script, under which directory, with which command?

**Comment by helevor** [comment]
Thank you for your quick answer ! It solved my problem.

Indeed I am trying to integrate your code in another project and I haven't noticed the update of config.
