### ISSUE TITLE
about the vis_decoder

### ISSUE THREAD

**Issue by ZZZGGGG** [zhiyuanyou/UniAD#24]
Hello, author, thank you very much for your work. I encountered some problems with vis_decoder when I reproduced your work. In your paper, I need to use the vis_decoder model to view reconstructed images, mainly the reverse process of resnet. My question is how can the exception be eliminated through this reverse process? May I ask your advice on this matter? I would appreciate it.

**Comment by zhiyuanyou** [comment]
Please see https://github.com/zhiyuanyou/UniAD/issues/9.
