### ISSUE TITLE
缺陷位置定位偏差

### ISSUE THREAD

**Issue by xaclincoln** [zhiyuanyou/UniAD#25]
在尝试将UniAD应用到公司的一个实际上项目上，发现缺陷位置与热力图总是一定的偏移，见下图
![企业微信截图_16899010928155](https://github.com/zhiyuanyou/UniAD/assets/10794955/faea1d5e-4e2b-4168-83f9-d5a52e93d85a)
![image](https://github.com/zhiyuanyou/UniAD/assets/10794955/45dce4b8-a06e-487e-960f-a9dde4336f7a)

尝试将NMA全部去除以及调整BackBone重新训练模型，位置偏差还是存在，思考了很久不知道该向哪个方向努力，想请教下这可能是哪里的问题？

**Comment by zhiyuanyou** [comment]
可能和缺陷的位置都在边缘有关，中间位置的可能好一些。

**Comment by zhiyuanyou** [comment]
另外，由于这个工作之前也有落地项目。我的经验是，在图片对齐性不是那么好的实际项目中，去除layer-wise query embedding，只保留第一个query embedding会好一些。在我做过的实际项目中，NMA和FJ都是十分有益的。

**Comment by xaclincoln** [comment]
尝试了去除decoder的query embedding, 仅保留第一个。结果有些改进，但是仍然有些图片有较大位置偏差
![image](https://github.com/zhiyuanyou/UniAD/assets/10794955/12e6a8a1-5050-4246-bc41-0c60b05a17dc)
![image](https://github.com/zhiyuanyou/UniAD/assets/10794955/1d09618e-dc71-497e-9295-0e7968698c0a)
![image](https://github.com/zhiyuanyou/UniAD/assets/10794955/35846c79-ee62-47ec-81e4-50ecab2f7b72)

我把除第一个Decoder中的query embedding的require_grad设置成false，权重仍然是随机初始化的。要不要把权重全部置为1？

**Comment by zhiyuanyou** [comment]
这个需要改decoder layer的结构，从3输入改成2输入，不是设置梯度为false就可以了，可以参考paper：[ADTR: Anomaly Detection Transformer with Feature Reconstruction](https://arxiv.org/pdf/2209.01816.pdf)。

**Comment by xaclincoln** [comment]
你好，我修改了模型结构，改成类似与原生Transformer结构，Decoder的第一个Attention模块使用上一个Decoder Layer，Decoder的第二个Attension，K和V来自Encoder的输出，Q来自于第一个Attension。4个Decoder中仅第一个Decoder的Query Embedding使用nn.Embedding, 但是结果仍然与上面相差无几。
![image](https://github.com/zhiyuanyou/UniAD/assets/10794955/8aa7e6bb-ccba-4af2-80e0-8a02bcf81aff)
代码截图如下：
![image](https://github.com/zhiyuanyou/UniAD/assets/10794955/7c141d9e-853d-4db0-9708-768040e43ba4)
![image](https://github.com/zhiyuanyou/UniAD/assets/10794955/41e5d7e1-1661-42b1-b37b-56b0cd32516c)

请教下，修改的是否有问题，还是说可能有其它原因导致位置偏差？

**Comment by zhiyuanyou** [comment]
Hi~


我个人认为主要是backbone提取特征的问题。对于靠近边缘的区域，其feature map和pixel对应的不是很好。所以会出现边缘部分定位不准确。


如果确实是这个问题的话，那就比较棘手了。可能可以尝试不同的backbone。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月28日(周五) 下午3:38
收件人: ***@***.***&gt;;
抄送: "You ***@***.******@***.***&gt;;
主题: Re: [zhiyuanyou/UniAD] 缺陷位置定位偏差 (Issue #25)




 
你好，我修改了模型结构，改成类似与原生Transformer结构，Decoder的第一个Attention模块使用上一个Decoder Layer，Decoder的第二个Attension，K和V来自Encoder的输出，Q来自于第一个Attension。4个Decoder中仅第一个Decoder的Query Embedding使用nn.Embedding, 但是结果仍然与上面相差无几。
 
 代码截图如下：
 
 
 
请教下，修改的是否有问题，还是说可能有其它原因导致位置偏差？

**Comment by hdmjdp** [comment]
@xaclincoln 可否分享一下如何训练自己的数据集，数据集构成方式

**Comment by hdmjdp** [comment]
@xaclincoln @zhiyuanyou 训练一定需要二值的ground truth mask吗
