### ISSUE TITLE
config.yaml 的一点问题

### ISSUE THREAD

**Issue by minglong-huang** [zhiyuanyou/UniAD#29]
作者，你好。
想问一下 在config.yaml中
port: 11111 是啥意思呀
以及如果要修改input_size的话 例如512,512   pixel_mean以及pixel_std需要修改吗
input_size: [224,224] # [h,w]
pixel_mean: [0.485, 0.456, 0.406]
pixel_std: [0.229, 0.224, 0.225]

**Comment by zhiyuanyou** [comment]
port是用于多卡通讯的端口号。
image size可以直接修改，不需要修改mean和std，但effecient net是在224的尺寸上训练的，512的尺寸效果不知道是否会变好。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月8日(周三) 下午5:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhiyuanyou/UniAD] config.yaml 的一点问题 (Issue #29)




 
作者，你好。
 想问一下 在config.yaml中
 port: 11111 是啥意思呀
 以及如果要修改input_size的话 例如512,512   pixel_mean以及pixel_std需要修改吗
 input_size: [224,224] # [h,w]
 pixel_mean: [0.485, 0.456, 0.406]
 pixel_std: [0.229, 0.224, 0.225]

**Comment by minglong-huang** [comment]
这个样子 哭死 我感觉我废了 跑了一下午 到现在没跑成功 将torch=2.1.0 换成了您那边的requirements.txt 结果与驱动不匹配 现在在装成torch ==1.13.1 与torchvision ==0.14.1 也报错 不知道作者有没有试过高版本的呀
&nbsp;


1079268520
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "You ***@***.***&gt;; 
发送时间: 2023年11月8日(星期三) 晚上8:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhiyuanyou/UniAD] config.yaml 的一点问题 (Issue #29)





 port是用于多卡通讯的端口号。 
 image size可以直接修改，不需要修改mean和std，但effecient net是在224的尺寸上训练的，512的尺寸效果不知道是否会变好。 
 
 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年11月8日(周三) 下午5:35 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [zhiyuanyou/UniAD] config.yaml 的一点问题 (Issue #29) 
 
 
 
 
   
 作者，你好。 
  想问一下 在config.yaml中 
  port: 11111 是啥意思呀 
  以及如果要修改input_size的话 例如512,512   pixel_mean以及pixel_std需要修改吗 
  input_size: [224,224] # [h,w] 
  pixel_mean: [0.485, 0.456, 0.406] 
  pixel_std: [0.229, 0.224, 0.225]

**Comment by zhiyuanyou** [comment]
代码在1.5和1.8的torch版本上验证过。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月8日(周三) 晚上8:37
收件人: ***@***.***&gt;;
抄送: "You ***@***.******@***.***&gt;;
主题: Re: [zhiyuanyou/UniAD] config.yaml 的一点问题 (Issue #29)




 这个样子 哭死 我感觉我废了 跑了一下午 到现在没跑成功 将torch=2.1.0 换成了您那边的requirements.txt 结果与驱动不匹配 现在在装成torch ==1.13.1 与torchvision ==0.14.1 也报错 不知道作者有没有试过高版本的呀 
 &amp;nbsp; 
 
 
 1079268520 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "You ***@***.***&amp;gt;;  
 发送时间: 2023年11月8日(星期三) 晚上8:33 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [zhiyuanyou/UniAD] config.yaml 的一点问题 (Issue #29) 
 
 
 
 
 
  port是用于多卡通讯的端口号。  
  image size可以直接修改，不需要修改mean和std，但effecient net是在224的尺寸上训练的，512的尺寸效果不知道是否会变好。  
   
   
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年11月8日(周三) 下午5:35  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: [zhiyuanyou/UniAD] config.yaml 的一点问题 (Issue #29)  
   
   
   
   
     
  作者，你好。  
   想问一下 在config.yaml中  
   port: 11111 是啥意思呀  
   以及如果要修改input_size的话 例如512,512   pixel_mean以及pixel_std需要修改吗  
   input_size: [224,224] # [h,w]  
   pixel_mean: [0.485, 0.456, 0.406]  
   pixel_std: [0.229, 0.224, 0.225]

**Comment by minglong-huang** [comment]
你好 终于跑起来了 因为我的是3090 在conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch 环境下跑起来了 本来想使用visualize reconstructed features 但是又报错了 暂时还未解决~ 奇奇怪怪的 哭死
