### ISSUE TITLE
How to get 128x128 cifar10 images?

### ISSUE THREAD

**Issue by coordxyz** [zhiyuanyou/UniAD#3]
If I simply resize the image with bicubic interplotation, the resized images will contain a lot of griding(chessboard) noise. I also find a 128x128 version of cifar10 by using super resolution tech from https://www.kaggle.com/datasets/joaopauloschuler/cifar10-128x128-resized-via-cai-super-resolution. But the SR images also contain lots of other kinds of artifacts. I guess all these artifacts will effect the AD performance. 
Do you have similar problem? How do you get the 128x128 size for cifar10 images whose original size is 32x32? 
Thx~

**Comment by zhiyuanyou** [comment]
We are now working to provide the CIFAR-10 results. The code would be released in one week. 

About how to resize, you could see Line103 of https://github.com/zhiyuanyou/UniAD/blob/main/datasets/cifar_dataset.py, *i.e.*, `transforms.Resize(resize, Image.ANTIALIAS)`.

**Comment by coordxyz** [comment]
Thanks, I'll try to use Image.ANTIALIAS rather than bicubic.

**Comment by zhiyuanyou** [comment]
We have added the CIFAR-10 results. If you still have questions, please re-open this issue.
