### ISSUE TITLE
关于模型的一些使用问题

### ISSUE THREAD

**Issue by minglong-huang** [zhiyuanyou/UniAD#30]
你好 在vis_query文件中的config.yaml 中出现了
saver:
  load_path: ../train_vis_decoder/{class_name}/checkpoints/ckpt.pth.tar
  save_dir: result_vis_query
  log_dir: log

vis_query:
  model_path: ../MVTec-AD/checkpoints/ckpt.pth.tar
  hidden_dim: 256
  num_decoder_layers: 4
  with_text: True
请问为什么saver中的load_path起什么作用呀
我训练完之后想要预测单张图片 我可以使用哪个文件的接口呀

**Comment by zhiyuanyou** [comment]
See Sec. 1.1 and Sec. 3.2 in README.
