### ISSUE TITLE
About the color jitter

### ISSUE THREAD

**Issue by cuicathy** [zhiyuanyou/UniAD#31]
Hi! Thanks for releasing the code of this great work. I have a question about the color jitter. Why is it only added in training but not in validation? I thought it was added to avoid reconstructing inputs through shortcuts. However, if it is only added in the training phase, it is more likely to be an augmentation.

**Comment by zhiyuanyou** [comment]
1. "Identical shortcut" is a problem brought by the training process. If the model has avoided the shortcut during the training, it is not necessary to use the feature jittering during testing. 
2. Also, all operations in test stage should be non-random, but feature jittering is random.

**Comment by cuicathy** [comment]
Thank you for your response. I have an additional question for clarification. As I understand it, abnormalities are identifiable due to their distinct feature distribution compared to normal data. The model never learns to reconstruct the abnormality in training and thus fails in the testing phase. However, if all images in the training phase were processed by the color jitter, is it possible that the normal images without color jitter will be detected as abnormal in the testing phase?
