### ISSUE TITLE
Training category issue

### ISSUE THREAD

**Issue by zxy200123** [zhiyuanyou/UniAD#32]
Hello, when using models to train my own dataset, I would like to ask the following questions:
Can all multi category data be trained in one train or do we need to place different category data in different folders?
2. If the feature maps that have been processed by NME and LQD are decoded into three features from high to low and compared with the original Resne feature extractor, will it result in inaccurate results?

**Comment by zhiyuanyou** [comment]
1. Only one folder is OK.
2. The results depends. It is better to compare both.

**Comment by zxy200123** [comment]
The training has ended, how many questions do I want to ask?
1.Before visualizing and reconstructing features? Is it necessary to train the vis_decoder.
2. During the training process of vis_decoder, I found that in the Resnet class, if self. installations==32:
Layer_strides=[2, 2, 2, 1]
Elif self. installations==16:
Layer_strides=[1, 2, 2, 1], what is this part for? During the training process, it resulted in a size of 7 * 7 and another size of 28 * 28 being unable to add.

**Comment by zhiyuanyou** [comment]
1. Yes.
2. "instrides" means the output_stride of the input feature, and there is no "installations". Pls see codes for detail. 

I can not understand other questions. It is better for you to polish the English a little after directly using the translation software.

**Comment by zxy200123** [comment]
在进行对VIS_decoder的训练过程中，在RESNET解码器中出现了The size of tensor a (7) must match the size of tensor b (28) at non-singleton dimension 3错误，错误好像是由        if self.instrides == 32:
            layer_strides = [2, 2, 2, 1]
        elif self.instrides == 16:
            layer_strides = [1, 2, 2,1]  引起的，我想问一下？这个  layer_strides需要根据什么调整。我使用的是RESNET101，也选择了Bottleneck.

**Comment by zhiyuanyou** [comment]
错误应该不是这里导致的。
这段代码的意思是：
如果input feature下采样的倍数是32，那么在第0层上采样4倍（默认），之后的[2, 2, 2, 1]表示在第1、2、3层分别上采样2倍。
如果input feature下采样的倍数是16，那么在第0层上采样4倍（默认），之后的[1, 2, 2, 1]表示在第2、3层分别上采样2倍。
