### ISSUE TITLE
tokenized the feature map

### ISSUE THREAD

**Issue by ghost** [zhiyuanyou/UniAD#34]
Thank you for your great work, I have a question.

In your paper, you said that you tokenized the feature map into H × W feature tokens using Corg channels, but I can't find the tokenization code in the code you provided. Could you please explain where I can find this part of the code and how I can try to tokenize it?
Also, may I ask why you are using the Model_helper class instead of using the UniAD model class?

**Comment by zhiyuanyou** [comment]
Thanks for your interest. 

tokenization: https://github.com/zhiyuanyou/UniAD/blob/main/models/reconstructions/uniad.py#L63
model_helper = backbone + neck + reconstruction. In this repo, only the reconstruction part is named as UniAD.

**Comment by ghost** [comment]
Thank you for your kind and clear respons. 👍

**Comment by ghost** [comment]
Can I ask an additional question? If I want to modify the structure of the uniAd model, how can I do that? Is it possible with the uniad.py file?

**Comment by zhiyuanyou** [comment]
Yes, you can modify the uniad.py file. You can also modify the backbone and neck parts.

**Comment by ghost** [comment]
If I modify the uniad.py file, will the changes be automatically applied when I train the model using model_helper.py?

**Comment by zhiyuanyou** [comment]
Yes. 

It is better to see and understand how this function works:  https://github.com/zhiyuanyou/UniAD/blob/main/models/model_helper.py#L30

**Comment by ghost** [comment]
Thank you, you have been a great help.
