### ISSUE TITLE
separate/unified case

### ISSUE THREAD

**Issue by ghost** [zhiyuanyou/UniAD#35]
Thank you for your great work, I have a question.

As you showed me, how can I do the separate/unified case experiment? 
Can I know how to change from unified case to separate case?

![캡처](https://github.com/user-attachments/assets/541254de-0dc7-46a0-9367-27914dcd6e3d)

**Comment by zhiyuanyou** [comment]
Hello, thanks for your interests to our work. The released code has been well tested and verified on the unified case, which is our main focus. If you want to test separate case, you need to adjust the dataset json file (construct dataset with only one class), and to re-train the model.

**Comment by ghost** [comment]
Thank you for your kind and clear respons. 👍
