### ISSUE TITLE
Test.json file

### ISSUE THREAD

**Issue by ghost** [zhiyuanyou/UniAD#36]
Hi! Thank you for your great work. I have a question. 
I want to evaluate uniad with a new dataset, but I encountered an issue when I modified the test.json file. If one test image has more than one mask image, can I know how to modify it?
In this case, do we only use one mask or do we have to use another method?

**Comment by zhiyuanyou** [comment]
Hello, thanks for your interests. 

However, I wonder why one image has more than one mask image? 

Is it because there are multiple ground truth?

**Comment by ghost** [comment]
Yes, there are multiple ground_truths. For example, for the MVTec-LOCO dataset, there are multiple ground_truths (logical_anomalies) for pushpins.

**Comment by zhiyuanyou** [comment]
Sorry that I am not familiar with MVTec-LOCO dataset. UniAD can only produce a single prediction. Maybe evaluating with every ground-truth mask is a possible solution.

**Comment by ghost** [comment]
Thank you for your thoughtful consideration and kind response to my question.
