### ISSUE TITLE
Why auc<0.5 auc=1-auc?

### ISSUE THREAD

**Issue by sherwin-silin-chen** [zhiyuanyou/UniAD#39]
In your evaluation code:
`if auc < 0.5: auc = 1 - auc`
Why??

**Comment by zhiyuanyou** [comment]
If AUC is smaller than 0.5, we can treat 0 as anomaly and 1 as normal, and this brings a new AUC value that equals 1 - AUC. 

In our experiments, all AUC are larger than 0.5, so **this case is never used**.
