### ISSUE TITLE
test_torch.sh

### ISSUE THREAD

**Issue by wyanb** [zhiyuanyou/UniAD#4]
Hello, could you upload the test file? Thank you.

**Comment by zhiyuanyou** [comment]
Hi~ Could you please clarify your question? For which dataset, in which case? If it is for MVTec-AD, you could run *eval.sh* or *eval_torch.sh* to test the model.

**Comment by wyanb** [comment]
Thank you for your answer. I understand

**Comment by zhiyuanyou** [comment]
I found that I wrote *test* in README but gave *eval* as the name of shell file. I will revise the README to make them consistent.
