### ISSUE TITLE
How to inference？

### ISSUE THREAD

**Issue by shellxiao** [zhiyuanyou/UniAD#8]
Thanks for your great work!
So, how to inference by one image?

**Comment by zhiyuanyou** [comment]
Well, we do not provide the tool for inference so far. Since you need this, we will discuss to add this. I think this could be completed in one week.

**Comment by zhiyuanyou** [comment]
If you are in urgent, you need to choose a *post-processing method* and a *threshold* through ***the evaluation results***. Then:
- Input an image to the network to get the anomaly map. 
- Calculate the anomaly score of the whole image with the ***given*** post-processing method.
- Compare the anomaly score with the ***given*** threshold. If bigger, this image is defective; else, this image is normal.

**Comment by shellxiao** [comment]
Thanks! I will have a try~

**Comment by zhiyuanyou** [comment]
Hi, 
I am very sorry to tell you that after our discussion, we finally decide ***not to provide the inference code***, since: 
- This code has no relationship with all contents in our published paper. 
- This code is associated with our practical usage and commercial projects.
