### ISSUE TITLE
why decoders need to re-trained for visualization?

### ISSUE THREAD

**Issue by fuweifuvtoo** [zhiyuanyou/UniAD#9]
Thanks for your excellent work!
But I wonder why decoders need to re-trained for visualization?

**Comment by zhiyuanyou** [comment]
We follow a feature-reconstruction paradigm. The reconstruction source and target are all features. These features are hard to visualize, especially hard to show the "shortcut problem". Therefore, we need some decoders to project these features to pixel space. So, these decoders are trained to ***project backbone-extracted features to pixel space***. 

Note that: 
- the backbone is pre-trained on ImageNet and fixed during training. 
- the decoders are trainable. ***In your comments, you used "re-trained", but it is not re-trained, but trained from the scratch***.

**Comment by fuweifuvtoo** [comment]
thanks for your helpful reply！
